export const countries = [
  { name: "Afghanistan", code: "+93", iso2: "af" },
  { name: "Albania", code: "+355", iso2: "al" },
  { name: "Algeria", code: "+213", iso2: "dz" },
  { name: "Andorra", code: "+376", iso2: "ad" },
  { name: "Angola", code: "+244", iso2: "ao" },
  { name: "Argentina", code: "+54", iso2: "ar" },
  { name: "Armenia", code: "+374", iso2: "am" },
  { name: "Australia", code: "+61", iso2: "au" },
  { name: "Austria", code: "+43", iso2: "at" },
  { name: "Azerbaijan", code: "+994", iso2: "az" },
  { name: "Bahrain", code: "+973", iso2: "bh" },
  { name: "Bangladesh", code: "+880", iso2: "bd" },
  { name: "Belarus", code: "+375", iso2: "by" },
  { name: "Belgium", code: "+32", iso2: "be" },
  { name: "Belize", code: "+501", iso2: "bz" },
  { name: "Benin", code: "+229", iso2: "bj" },
  { name: "Bhutan", code: "+975", iso2: "bt" },
  { name: "Bolivia", code: "+591", iso2: "bo" },
  { name: "Bosnia and Herzegovina", code: "+387", iso2: "ba" },
  { name: "Botswana", code: "+267", iso2: "bw" },
  { name: "Brazil", code: "+55", iso2: "br" },
  { name: "Brunei", code: "+673", iso2: "bn" },
  { name: "Bulgaria", code: "+359", iso2: "bg" },
  { name: "Burkina Faso", code: "+226", iso2: "bf" },
  { name: "Burundi", code: "+257", iso2: "bi" },
  { name: "Cambodia", code: "+855", iso2: "kh" },
  { name: "Cameroon", code: "+237", iso2: "cm" },
  { name: "Canada", code: "+1", iso2: "ca" },
  { name: "Cape Verde", code: "+238", iso2: "cv" },
  { name: "Central African Republic", code: "+236", iso2: "cf" },
  { name: "Chad", code: "+235", iso2: "td" },
  { name: "Chile", code: "+56", iso2: "cl" },
  { name: "China", code: "+86", iso2: "cn" },
  { name: "Colombia", code: "+57", iso2: "co" },
  { name: "Comoros", code: "+269", iso2: "km" },
  { name: "Costa Rica", code: "+506", iso2: "cr" },
  { name: "Croatia", code: "+385", iso2: "hr" },
  { name: "Cuba", code: "+53", iso2: "cu" },
  { name: "Cyprus", code: "+357", iso2: "cy" },
  { name: "Czech Republic", code: "+420", iso2: "cz" },
  { name: "Denmark", code: "+45", iso2: "dk" },
  { name: "Djibouti", code: "+253", iso2: "dj" },
  { name: "Ecuador", code: "+593", iso2: "ec" },
  { name: "Egypt", code: "+20", iso2: "eg" },
  { name: "El Salvador", code: "+503", iso2: "sv" },
  { name: "Equatorial Guinea", code: "+240", iso2: "gq" },
  { name: "Eritrea", code: "+291", iso2: "er" },
  { name: "Estonia", code: "+372", iso2: "ee" },
  { name: "Ethiopia", code: "+251", iso2: "et" },
  { name: "Fiji", code: "+679", iso2: "fj" },
  { name: "Finland", code: "+358", iso2: "fi" },
  { name: "France", code: "+33", iso2: "fr" },
  { name: "Georgia", code: "+995", iso2: "ge" },
  { name: "Germany", code: "+49", iso2: "de" },
  { name: "Ghana", code: "+233", iso2: "gh" },
  { name: "Greece", code: "+30", iso2: "gr" },
  { name: "Greenland", code: "+299", iso2: "gl" },
  { name: "Guatemala", code: "+502", iso2: "gt" },
  { name: "Guinea", code: "+224", iso2: "gn" },
  { name: "Guyana", code: "+592", iso2: "gy" },
  { name: "Haiti", code: "+509", iso2: "ht" },
  { name: "Honduras", code: "+504", iso2: "hn" },
  { name: "Hungary", code: "+36", iso2: "hu" },
  { name: "Iceland", code: "+354", iso2: "is" },
  { name: "India", code: "+91", iso2: "in" },
  { name: "Indonesia", code: "+62", iso2: "id" },
  { name: "Iran", code: "+98", iso2: "ir" },
  { name: "Iraq", code: "+964", iso2: "iq" },
  { name: "Ireland", code: "+353", iso2: "ie" },
  { name: "Israel", code: "+972", iso2: "il" },
  { name: "Italy", code: "+39", iso2: "it" },
  { name: "Japan", code: "+81", iso2: "jp" },
  { name: "Jordan", code: "+962", iso2: "jo" },
  { name: "Kazakhstan", code: "+7", iso2: "kz" },
  { name: "Kenya", code: "+254", iso2: "ke" },
  { name: "Kuwait", code: "+965", iso2: "kw" },
  { name: "Kyrgyzstan", code: "+996", iso2: "kg" },
  { name: "Latvia", code: "+371", iso2: "lv" },
  { name: "Lebanon", code: "+961", iso2: "lb" },
  { name: "Lithuania", code: "+370", iso2: "lt" },
  { name: "Luxembourg", code: "+352", iso2: "lu" },
  { name: "Malaysia", code: "+60", iso2: "my" },
  { name: "Mexico", code: "+52", iso2: "mx" },
  { name: "Netherlands", code: "+31", iso2: "nl" },
  { name: "New Zealand", code: "+64", iso2: "nz" },
  { name: "Norway", code: "+47", iso2: "no" },
  { name: "Pakistan", code: "+92", iso2: "pk" },
  { name: "Philippines", code: "+63", iso2: "ph" },
  { name: "Poland", code: "+48", iso2: "pl" },
  { name: "Portugal", code: "+351", iso2: "pt" },
  { name: "Romania", code: "+40", iso2: "ro" },
  { name: "Russia", code: "+7", iso2: "ru" },
  { name: "Saudi Arabia", code: "+966", iso2: "sa" },
  { name: "Serbia", code: "+381", iso2: "rs" },
  { name: "Singapore", code: "+65", iso2: "sg" },
  { name: "Slovakia", code: "+421", iso2: "sk" },
  { name: "Slovenia", code: "+386", iso2: "si" },
  { name: "South Africa", code: "+27", iso2: "za" },
  { name: "South Korea", code: "+82", iso2: "kr" },
  { name: "Spain", code: "+34", iso2: "es" },
  { name: "Sweden", code: "+46", iso2: "se" },
  { name: "Switzerland", code: "+41", iso2: "ch" },
  { name: "Thailand", code: "+66", iso2: "th" },
  { name: "Turkey", code: "+90", iso2: "tr" },
  { name: "Ukraine", code: "+380", iso2: "ua" },
  { name: "United Arab Emirates", code: "+971", iso2: "ae" },
  { name: "United Kingdom", code: "+44", iso2: "gb" },
  { name: "United States", code: "+1", iso2: "us" },
  { name: "Vietnam", code: "+84", iso2: "vn" },
];

countries.sort((a, b) => a.name.localeCompare(b.name));